In [1]:
import pandas as pd
import math

# Create a DataFrame with the provided data

data = [
    ["<=30","high", "no", "fair", "no"],
    ["<=30","high", "no", "excellent",  "no"],
    [ "31…40","high", "no", "fair", "yes"],
    [ ">40","medium", "no", "fair", "yes"],
    [">40","low", "yes", "fair",  "yes"],
    [ ">40","low", "yes", "excellent", "no"],
    [ "30...40", "low", "yes", "excellent","yes"],
    [ "<=30", "medium", "no", "fair","no"],
    ["<=30", "low", "yes", "fair", "yes"],
    [">40", "medium", "yes", "fair", "yes"],
    ["<=30", "medium", "yes", "excellent", "yes"],
    ["31...40", "medium", "no","excellent", "yes"],
    ["31...40", "high", "yes","fair", "yes"],
    [">40", "medium", "no", "excellent", "no"],
]

# Create a Pandas DataFrame
df = pd.DataFrame(data, columns=["age", "income", "student", "credit_rating", "buys_computer"])

In [2]:
df

        age  income student credit_rating buys_computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2     31…40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   30...40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  31...40  medium      no     excellent           yes
12  31...40    high     yes          fair           yes
13      >40  medium      no     excellent            no

In [3]:
buys_computer = [row[-1] for row in data]

# Counting occurrences of each class
class_counts = {}
total_instances = len(buys_computer)

for label in buys_computer:
    if label in class_counts:
        class_counts[label] += 1
    else:
        class_counts[label] = 1

# Calculating prior probabilities
prior_probabilities = {}
for label, count in class_counts.items():
    prior_probabilities[label] = count / total_instances

# Displaying prior probabilities
print("Prior probabilities for each class:")
for label, probability in prior_probabilities.items():
    print(f"{label}: {probability:.4f}")

Prior probabilities for each class:
no: 0.3571
yes: 0.6429

In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"
      % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 75 points : 4